brace_style = "PreferSameLine"
control_brace_style = "AlwaysSameLine"
fn_args_layout = "Compressed"
format_code_in_doc_comments = true
format_macro_matchers = true
match_block_trailing_comma = true
merge_imports = true