[package]
name = "coolq-sdk-rust"
version = "0.0.2"
authors = ["soeur <juzi201314@gmail.com>"]
edition = "2018"

[dependencies]
encoding = "0.2.33"
lazy_static = "1.2.0"
#dirmod = "0.2.0-alpha.1"
base64 = "0.11.0"
byteorder = "1.3.2"
uuid = { version = "0.8.1", features = ["v4"]}
reqwest = "0.9.22"
regex = "1.3.1"

[profile.release]
opt-level = 3
lto = true
debug = false
codegen-units = 1
panic = "abort"