[package]
name = "coolq-sdk-rust"
version = "0.0.2"
authors = ["soeur <juzi201314@gmail.com>"]
edition = "2018"

[dependencies]
encoding = "0.2.33"
lazy_static = "1.2.0"
#dirmod = "0.2.0-alpha.1"
base64 = "0.11.0"
byteorder = "1.3.2"